-- require("plugins.coc")
require("plugins.packer")
require("plugins.dashboard")
require("plugins.lualine")
require("plugins.nerdcommenter")
require("plugins.nvim-compe")
require("plugins.saga")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.web-devicons")
require("plugins.zenmode")
require("plugins.twilight")
-- require("plugins.lspinstall")
