require 'lsp.capabilities'
require 'lsp.bash-ls'
require 'lsp.clangd'
require 'lsp.css-ls'
require 'lsp.efm-ls'
require 'lsp.html'
require 'lsp.latex-ls'
require 'lsp.lua-ls'
require 'lsp.python-ls'
require 'lsp.rust-ls'
require 'lsp.tsserver'
require 'lsp.vim-ls'
-- require 'lsp.java-ls'
